/**
 * Created by mkash32 on 18/1/16.
 */

module.exports.url_template = 'https://<host>/<ver>/<ac>/<uid[0]>/<uid[1]>/<asalk>';
module.exports.currentAPIVersion = '1.6';   //current version of the Aadhaar Auth API, if API is updated then this constant should be changed

//txn :- transaction id for AUA, generated by AUA
//lk: -liscense key, assigned to the AUA. Available on Administration portal
//Lot :- G or P depending on whether to giv lat/long or postal code
//type :- PID type
//UDC :- Unique Device Code, should be unique for every device that requests this information (Alpha numeric string of max length 20)
//          [vendorcode][date of deployment][serial number]
//ci :- expiry date of the certificate, should be of the form YYYYMMDD
//      current certificate has expiration date of 16 Sept 2020, 20200916


module.exports.public_config_attrs = {
    "asalk":"MLTbKYcsgYMq1zgL3WMZYrnyvsarlljxpom2A-QTPc0Zud23shpnqPk",
    "ac":"public",
    "sa":"public",
    "tid":"public",
    "ver": "1.6",
    "txn": "TBD",
    "lk": "MLTbKYcsgYMq1zgL3WMZYrnyvsarlljxpom2A-QTPc0Zud23shpnqPk",
    "pi": "y",
    "udc": "TBD",
    "fdc": "NA",
    "idc": "NA",
    "pip": "NA",
    "lot": "P",
    "type":"X",
    "ci": "20200916"
};

module.exports.basic_uses_attrs = {
    "pi": "y",
    "pa": "n",
    "pfa": "n",
    "bio": "n",
    "bt": "n",
    "pin": "n",
    "otp": "n"
}